diff a/Makefile b/Makefile	(rejected hunks)
@@ -1,6 +1,6 @@
 TOOLCHAIN		?=	/home/tavisco/Palm/palmdev_V3/buildtools/toolchain/bin
 SDK				?=	/home/tavisco/Palm/palmdev_V3/buildtools/palm-os-sdk-master/sdk-5r3/include
-PILRC			=	/home/tavisco/Palm/palmdev_V3/buildtools/pilrc3_3_unofficial/bin/pilrc
+PILRC			?=	/home/tavisco/Palm/palmdev_V3/buildtools/pilrc3_3_unofficial/bin/pilrc
 CC				=	$(TOOLCHAIN)/m68k-none-elf-gcc
 LD				=	$(TOOLCHAIN)/m68k-none-elf-gcc
 OBJCOPY			=	$(TOOLCHAIN)/m68k-none-elf-objcopy
@@ -9,11 +9,10 @@ WARN			=	-Wsign-compare -Wextra -Wall -Wno-unused-parameter -Wno-old-style-decla
 LKR				=	linker.lkr
 CCFLAGS			=	$(LTO) $(WARN) $(COMMON) -I. -ffunction-sections -fdata-sections
 LDFLAGS			=	$(LTO) $(WARN) $(COMMON) -Wl,--gc-sections -Wl,-T $(LKR)
-SRCS			=   Src/Palmkedex.c Src/Main.c Src/PkmnMain.c Src/PkmnType.c Src/helpers.c Src/miniz.c Src/pngle.c
+SRCS-68k		=   Src/Palmkedex.c Src/Main.c Src/PkmnMain.c Src/PkmnType.c Src/helpers.c Src/miniz.c Src/pngle.c Src/pngDraw.c
 RCP				=	Rsc/Palmkedex_Rsc.rcp
 SPRITESRCP		=	Rsc/pkmn_sprites.rcp
 RSC				=	Src/
-OBJS			=	$(patsubst %.S,%.o,$(patsubst %.c,%.o,$(SRCS)))
 TARGET			=	Palmkedex
 TARGETSPRITES	=	PalmkedexSprites
 CREATOR			=	PKDX
@@ -32,18 +31,22 @@ INCS			+=	-isystem "$(SDK)/Dynamic"
 INCS			+=	-isystem "$(SDK)/Libraries"
 INCS			+=	-isystem "$(SDK)/Libraries/PalmOSGlue"
 
+#leave this alone
+OBJS-68k		=	$(patsubst %.S,%.68k.o,$(patsubst %.c,%.68k.o,$(SRCS-68k)))
+
+
 all: $(TARGET).prc $(TARGETSPRITES).prc
 
-$(TARGET).prc: code0001.bin
-	$(PILRC) -ro -o $(TARGET).prc -creator $(CREATOR) -type $(TYPE) -name $(TARGET) -I $(RSC) $(RCP) && rm code0001.bin
+$(TARGET).prc: code0001.68k.bin
+	$(PILRC) -ro -o $(TARGET).prc -creator $(CREATOR) -type $(TYPE) -name $(TARGET) -I $(RSC) $(RCP)
 
-%.bin: %.elf
+%.68k.bin: %.68k.elf
 	$(OBJCOPY) -O binary $< $@ -j.vec -j.text -j.rodata
 
-%.elf: $(OBJS)
+%.68k.elf: $(OBJS-68k)
 	$(LD) -o $@ $(LDFLAGS) $^
 
-%.o : %.c Makefile
+%.68k.o : %.c Makefile
 	$(CC) $(CCFLAGS)  $(INCS) -c $< -o $@
 
 $(TARGETSPRITES).prc:
@@ -51,4 +54,4 @@ $(TARGETSPRITES).prc:
 
 .PHONY: clean
 clean:
-	rm -rf $(OBJS) $(NAME).elf
\ No newline at end of file
+	rm -rf $(OBJS-68k) $(TARGET).prc $(TARGETSPRITES).prc
\ No newline at end of file
