#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>



static char pkmnsNames[][13] = {
{"Bulbasaur"},
{"Ivysaur"},
{"Venusaur"},
{"Charmander"},
{"Charmeleon"},
{"Charizard"},
{"Squirtle"},
{"Wartortle"},
{"Blastoise"},
{"Caterpie"},
{"Metapod"},
{"Butterfree"},
{"Weedle"},
{"Kakuna"},
{"Beedrill"},
{"Pidgey"},
{"Pidgeotto"},
{"Pidgeot"},
{"Rattata"},
{"Raticate"},
{"Spearow"},
{"Fearow"},
{"Ekans"},
{"Arbok"},
{"Pikachu"},
{"Raichu"},
{"Sandshrew"},
{"Sandslash"},
{"Nidoran-f"},
{"Nidorina"},
{"Nidoqueen"},
{"Nidoran-m"},
{"Nidorino"},
{"Nidoking"},
{"Clefairy"},
{"Clefable"},
{"Vulpix"},
{"Ninetales"},
{"Jigglypuff"},
{"Wigglytuff"},
{"Zubat"},
{"Golbat"},
{"Oddish"},
{"Gloom"},
{"Vileplume"},
{"Paras"},
{"Parasect"},
{"Venonat"},
{"Venomoth"},
{"Diglett"},
{"Dugtrio"},
{"Meowth"},
{"Persian"},
{"Psyduck"},
{"Golduck"},
{"Mankey"},
{"Primeape"},
{"Growlithe"},
{"Arcanine"},
{"Poliwag"},
{"Poliwhirl"},
{"Poliwrath"},
{"Abra"},
{"Kadabra"},
{"Alakazam"},
{"Machop"},
{"Machoke"},
{"Machamp"},
{"Bellsprout"},
{"Weepinbell"},
{"Victreebel"},
{"Tentacool"},
{"Tentacruel"},
{"Geodude"},
{"Graveler"},
{"Golem"},
{"Ponyta"},
{"Rapidash"},
{"Slowpoke"},
{"Slowbro"},
{"Magnemite"},
{"Magneton"},
{"Farfetchd"},
{"Doduo"},
{"Dodrio"},
{"Seel"},
{"Dewgong"},
{"Grimer"},
{"Muk"},
{"Shellder"},
{"Cloyster"},
{"Gastly"},
{"Haunter"},
{"Gengar"},
{"Onix"},
{"Drowzee"},
{"Hypno"},
{"Krabby"},
{"Kingler"},
{"Voltorb"},
{"Electrode"},
{"Exeggcute"},
{"Exeggutor"},
{"Cubone"},
{"Marowak"},
{"Hitmonlee"},
{"Hitmonchan"},
{"Lickitung"},
{"Koffing"},
{"Weezing"},
{"Rhyhorn"},
{"Rhydon"},
{"Chansey"},
{"Tangela"},
{"Kangaskhan"},
{"Horsea"},
{"Seadra"},
{"Goldeen"},
{"Seaking"},
{"Staryu"},
{"Starmie"},
{"Mr Mime"},
{"Scyther"},
{"Jynx"},
{"Electabuzz"},
{"Magmar"},
{"Pinsir"},
{"Tauros"},
{"Magikarp"},
{"Gyarados"},
{"Lapras"},
{"Ditto"},
{"Eevee"},
{"Vaporeon"},
{"Jolteon"},
{"Flareon"},
{"Porygon"},
{"Omanyte"},
{"Omastar"},
{"Kabuto"},
{"Kabutops"},
{"Aerodactyl"},
{"Snorlax"},
{"Articuno"},
{"Zapdos"},
{"Moltres"},
{"Dratini"},
{"Dragonair"},
{"Dragonite"},
{"Mewtwo"},
{"Mew"},
{"Chikorita"},
{"Bayleef"},
{"Meganium"},
{"Cyndaquil"},
{"Quilava"},
{"Typhlosion"},
{"Totodile"},
{"Croconaw"},
{"Feraligatr"},
{"Sentret"},
{"Furret"},
{"Hoothoot"},
{"Noctowl"},
{"Ledyba"},
{"Ledian"},
{"Spinarak"},
{"Ariados"},
{"Crobat"},
{"Chinchou"},
{"Lanturn"},
{"Pichu"},
{"Cleffa"},
{"Igglybuff"},
{"Togepi"},
{"Togetic"},
{"Natu"},
{"Xatu"},
{"Mareep"},
{"Flaaffy"},
{"Ampharos"},
{"Bellossom"},
{"Marill"},
{"Azumarill"},
{"Sudowoodo"},
{"Politoed"},
{"Hoppip"},
{"Skiploom"},
{"Jumpluff"},
{"Aipom"},
{"Sunkern"},
{"Sunflora"},
{"Yanma"},
{"Wooper"},
{"Quagsire"},
{"Espeon"},
{"Umbreon"},
{"Murkrow"},
{"Slowking"},
{"Misdreavus"},
{"Unown"},
{"Wobbuffet"},
{"Girafarig"},
{"Pineco"},
{"Forretress"},
{"Dunsparce"},
{"Gligar"},
{"Steelix"},
{"Snubbull"},
{"Granbull"},
{"Qwilfish"},
{"Scizor"},
{"Shuckle"},
{"Heracross"},
{"Sneasel"},
{"Teddiursa"},
{"Ursaring"},
{"Slugma"},
{"Magcargo"},
{"Swinub"},
{"Piloswine"},
{"Corsola"},
{"Remoraid"},
{"Octillery"},
{"Delibird"},
{"Mantine"},
{"Skarmory"},
{"Houndour"},
{"Houndoom"},
{"Kingdra"},
{"Phanpy"},
{"Donphan"},
{"Porygon2"},
{"Stantler"},
{"Smeargle"},
{"Tyrogue"},
{"Hitmontop"},
{"Smoochum"},
{"Elekid"},
{"Magby"},
{"Miltank"},
{"Blissey"},
{"Raikou"},
{"Entei"},
{"Suicune"},
{"Larvitar"},
{"Pupitar"},
{"Tyranitar"},
{"Lugia"},
{"Ho-oh"},
{"Celebi"},
{"Treecko"},
{"Grovyle"},
{"Sceptile"},
{"Torchic"},
{"Combusken"},
{"Blaziken"},
{"Mudkip"},
{"Marshtomp"},
{"Swampert"},
{"Poochyena"},
{"Mightyena"},
{"Zigzagoon"},
{"Linoone"},
{"Wurmple"},
{"Silcoon"},
{"Beautifly"},
{"Cascoon"},
{"Dustox"},
{"Lotad"},
{"Lombre"},
{"Ludicolo"},
{"Seedot"},
{"Nuzleaf"},
{"Shiftry"},
{"Taillow"},
{"Swellow"},
{"Wingull"},
{"Pelipper"},
{"Ralts"},
{"Kirlia"},
{"Gardevoir"},
{"Surskit"},
{"Masquerain"},
{"Shroomish"},
{"Breloom"},
{"Slakoth"},
{"Vigoroth"},
{"Slaking"},
{"Nincada"},
{"Ninjask"},
{"Shedinja"},
{"Whismur"},
{"Loudred"},
{"Exploud"},
{"Makuhita"},
{"Hariyama"},
{"Azurill"},
{"Nosepass"},
{"Skitty"},
{"Delcatty"},
{"Sableye"},
{"Mawile"},
{"Aron"},
{"Lairon"},
{"Aggron"},
{"Meditite"},
{"Medicham"},
{"Electrike"},
{"Manectric"},
{"Plusle"},
{"Minun"},
{"Volbeat"},
{"Illumise"},
{"Roselia"},
{"Gulpin"},
{"Swalot"},
{"Carvanha"},
{"Sharpedo"},
{"Wailmer"},
{"Wailord"},
{"Numel"},
{"Camerupt"},
{"Torkoal"},
{"Spoink"},
{"Grumpig"},
{"Spinda"},
{"Trapinch"},
{"Vibrava"},
{"Flygon"},
{"Cacnea"},
{"Cacturne"},
{"Swablu"},
{"Altaria"},
{"Zangoose"},
{"Seviper"},
{"Lunatone"},
{"Solrock"},
{"Barboach"},
{"Whiscash"},
{"Corphish"},
{"Crawdaunt"},
{"Baltoy"},
{"Claydol"},
{"Lileep"},
{"Cradily"},
{"Anorith"},
{"Armaldo"},
{"Feebas"},
{"Milotic"},
{"Castform"},
{"Kecleon"},
{"Shuppet"},
{"Banette"},
{"Duskull"},
{"Dusclops"},
{"Tropius"},
{"Chimecho"},
{"Absol"},
{"Wynaut"},
{"Snorunt"},
{"Glalie"},
{"Spheal"},
{"Sealeo"},
{"Walrein"},
{"Clamperl"},
{"Huntail"},
{"Gorebyss"},
{"Relicanth"},
{"Luvdisc"},
{"Bagon"},
{"Shelgon"},
{"Salamence"},
{"Beldum"},
{"Metang"},
{"Metagross"},
{"Regirock"},
{"Regice"},
{"Registeel"},
{"Latias"},
{"Latios"},
{"Kyogre"},
{"Groudon"},
{"Rayquaza"},
{"Jirachi"},
{"Deoxys"},
{"Turtwig"},
{"Grotle"},
{"Torterra"},
{"Chimchar"},
{"Monferno"},
{"Infernape"},
{"Piplup"},
{"Prinplup"},
{"Empoleon"},
{"Starly"},
{"Staravia"},
{"Staraptor"},
{"Bidoof"},
{"Bibarel"},
{"Kricketot"},
{"Kricketune"},
{"Shinx"},
{"Luxio"},
{"Luxray"},
{"Budew"},
{"Roserade"},
{"Cranidos"},
{"Rampardos"},
{"Shieldon"},
{"Bastiodon"},
{"Burmy"},
{"Wormadam"},
{"Mothim"},
{"Combee"},
{"Vespiquen"},
{"Pachirisu"},
{"Buizel"},
{"Floatzel"},
{"Cherubi"},
{"Cherrim"},
{"Shellos"},
{"Gastrodon"},
{"Ambipom"},
{"Drifloon"},
{"Drifblim"},
{"Buneary"},
{"Lopunny"},
{"Mismagius"},
{"Honchkrow"},
{"Glameow"},
{"Purugly"},
{"Chingling"},
{"Stunky"},
{"Skuntank"},
{"Bronzor"},
{"Bronzong"},
{"Bonsly"},
{"Mime Jr"},
{"Happiny"},
{"Chatot"},
{"Spiritomb"},
{"Gible"},
{"Gabite"},
{"Garchomp"},
{"Munchlax"},
{"Riolu"},
{"Lucario"},
{"Hippopotas"},
{"Hippowdon"},
{"Skorupi"},
{"Drapion"},
{"Croagunk"},
{"Toxicroak"},
{"Carnivine"},
{"Finneon"},
{"Lumineon"},
{"Mantyke"},
{"Snover"},
{"Abomasnow"},
{"Weavile"},
{"Magnezone"},
{"Lickilicky"},
{"Rhyperior"},
{"Tangrowth"},
{"Electivire"},
{"Magmortar"},
{"Togekiss"},
{"Yanmega"},
{"Leafeon"},
{"Glaceon"},
{"Gliscor"},
{"Mamoswine"},
{"Porygon-Z"},
{"Gallade"},
{"Probopass"},
{"Dusknoir"},
{"Froslass"},
{"Rotom"},
{"Uxie"},
{"Mesprit"},
{"Azelf"},
{"Dialga"},
{"Palkia"},
{"Heatran"},
{"Regigigas"},
{"Giratina"},
{"Cresselia"},
{"Phione"},
{"Manaphy"},
{"Darkrai"},
{"Shaymin"},
{"Arceus"},
{"Victini"},
{"Snivy"},
{"Servine"},
{"Serperior"},
{"Tepig"},
{"Pignite"},
{"Emboar"},
{"Oshawott"},
{"Dewott"},
{"Samurott"},
{"Patrat"},
{"Watchog"},
{"Lillipup"},
{"Herdier"},
{"Stoutland"},
{"Purrloin"},
{"Liepard"},
{"Pansage"},
{"Simisage"},
{"Pansear"},
{"Simisear"},
{"Panpour"},
{"Simipour"},
{"Munna"},
{"Musharna"},
{"Pidove"},
{"Tranquill"},
{"Unfezant"},
{"Blitzle"},
{"Zebstrika"},
{"Roggenrola"},
{"Boldore"},
{"Gigalith"},
{"Woobat"},
{"Swoobat"},
{"Drilbur"},
{"Excadrill"},
{"Audino"},
{"Timburr"},
{"Gurdurr"},
{"Conkeldurr"},
{"Tympole"},
{"Palpitoad"},
{"Seismitoad"},
{"Throh"},
{"Sawk"},
{"Sewaddle"},
{"Swadloon"},
{"Leavanny"},
{"Venipede"},
{"Whirlipede"},
{"Scolipede"},
{"Cottonee"},
{"Whimsicott"},
{"Petilil"},
{"Lilligant"},
{"Basculin"},
{"Sandile"},
{"Krokorok"},
{"Krookodile"},
{"Darumaka"},
{"Darmanitan"},
{"Maractus"},
{"Dwebble"},
{"Crustle"},
{"Scraggy"},
{"Scrafty"},
{"Sigilyph"},
{"Yamask"},
{"Cofagrigus"},
{"Tirtouga"},
{"Carracosta"},
{"Archen"},
{"Archeops"},
{"Trubbish"},
{"Garbodor"},
{"Zorua"},
{"Zoroark"},
{"Minccino"},
{"Cinccino"},
{"Gothita"},
{"Gothorita"},
{"Gothitelle"},
{"Solosis"},
{"Duosion"},
{"Reuniclus"},
{"Ducklett"},
{"Swanna"},
{"Vanillite"},
{"Vanillish"},
{"Vanilluxe"},
{"Deerling"},
{"Sawsbuck"},
{"Emolga"},
{"Karrablast"},
{"Escavalier"},
{"Foongus"},
{"Amoonguss"},
{"Frillish"},
{"Jellicent"},
{"Alomomola"},
{"Joltik"},
{"Galvantula"},
{"Ferroseed"},
{"Ferrothorn"},
{"Klink"},
{"Klang"},
{"Klinklang"},
{"Tynamo"},
{"Eelektrik"},
{"Eelektross"},
{"Elgyem"},
{"Beheeyem"},
{"Litwick"},
{"Lampent"},
{"Chandelure"},
{"Axew"},
{"Fraxure"},
{"Haxorus"},
{"Cubchoo"},
{"Beartic"},
{"Cryogonal"},
{"Shelmet"},
{"Accelgor"},
{"Stunfisk"},
{"Mienfoo"},
{"Mienshao"},
{"Druddigon"},
{"Golett"},
{"Golurk"},
{"Pawniard"},
{"Bisharp"},
{"Bouffalant"},
{"Rufflet"},
{"Braviary"},
{"Vullaby"},
{"Mandibuzz"},
{"Heatmor"},
{"Durant"},
{"Deino"},
{"Zweilous"},
{"Hydreigon"},
{"Larvesta"},
{"Volcarona"},
{"Cobalion"},
{"Terrakion"},
{"Virizion"},
{"Tornadus"},
{"Thundurus"},
{"Reshiram"},
{"Zekrom"},
{"Landorus"},
{"Kyurem"},
{"Keldeo"},
{"Meloetta"},
{"Genesect"},
{"Chespin"},
{"Quilladin"},
{"Chesnaught"},
{"Fennekin"},
{"Braixen"},
{"Delphox"},
{"Froakie"},
{"Frogadier"},
{"Greninja"},
{"Bunnelby"},
{"Diggersby"},
{"Fletchling"},
{"Fletchinder"},
{"Talonflame"},
{"Scatterbug"},
{"Spewpa"},
{"Vivillon"},
{"Litleo"},
{"Pyroar"},
{"Flabebe"},
{"Floette"},
{"Florges"},
{"Skiddo"},
{"Gogoat"},
{"Pancham"},
{"Pangoro"},
{"Furfrou"},
{"Espurr"},
{"Meowstic"},
{"Honedge"},
{"Doublade"},
{"Aegislash"},
{"Spritzee"},
{"Aromatisse"},
{"Swirlix"},
{"Slurpuff"},
{"Inkay"},
{"Malamar"},
{"Binacle"},
{"Barbaracle"},
{"Skrelp"},
{"Dragalge"},
{"Clauncher"},
{"Clawitzer"},
{"Helioptile"},
{"Heliolisk"},
{"Tyrunt"},
{"Tyrantrum"},
{"Amaura"},
{"Aurorus"},
{"Sylveon"},
{"Hawlucha"},
{"Dedenne"},
{"Carbink"},
{"Goomy"},
{"Sliggoo"},
{"Goodra"},
{"Klefki"},
{"Phantump"},
{"Trevenant"},
{"Pumpkaboo"},
{"Gourgeist"},
{"Bergmite"},
{"Avalugg"},
{"Noibat"},
{"Noivern"},
{"Xerneas"},
{"Yveltal"},
{"Zygarde"},
{"Diancie"},
{"Hoopa"},
{"Volcanion"},
{"Rowlet"},
{"Dartrix"},
{"Decidueye"},
{"Litten"},
{"Torracat"},
{"Incineroar"},
{"Popplio"},
{"Brionne"},
{"Primarina"},
{"Pikipek"},
{"Trumbeak"},
{"Toucannon"},
{"Yungoos"},
{"Gumshoos"},
{"Grubbin"},
{"Charjabug"},
{"Vikavolt"},
{"Crabrawler"},
{"Crabominable"},
{"Oricorio"},
{"Cutiefly"},
{"Ribombee"},
{"Rockruff"},
{"Lycanroc"},
{"Wishiwashi"},
{"Mareanie"},
{"Toxapex"},
{"Mudbray"},
{"Mudsdale"},
{"Dewpider"},
{"Araquanid"},
{"Fomantis"},
{"Lurantis"},
{"Morelull"},
{"Shiinotic"},
{"Salandit"},
{"Salazzle"},
{"Stufful"},
{"Bewear"},
{"Bounsweet"},
{"Steenee"},
{"Tsareena"},
{"Comfey"},
{"Oranguru"},
{"Passimian"},
{"Wimpod"},
{"Golisopod"},
{"Sandygast"},
{"Palossand"},
{"Pyukumuku"},
{"Drampa"},
{"Silvally"},
{"Minior"},
{"Komala"},
{"Turtonator"},
{"Togedemaru"},
{"Mimikyu"},
{"Bruxish"},
{"Drampa"},
{"Dhelmise"},
{"Jangmo-o"},
{"Hakamo-o"},
{"Kommo-o"},
{"Tapu Koko"},
{"Tapu Lele"},
{"Tapu Bulu"},
{"Tapu Fini"},
{"Cosmog"},
{"Cosmoem"},
{"Solgaleo"},
{"Lunala"},
{"Nihilego"},
{"Buzzwole"},
{"Pheromosa"},
{"Xurkitree"},
{"Celesteela"},
{"Kartana"},
{"Guzzlord"},
{"Necrozma"},
{"Magearna"},
{"Marshadow"},
{"Poipole"},
{"Naganadel"},
{"Stakataka"},
{"Blacephalon"},
{"Zeraora"},
{"Meltan"},
{"Melmetal"},
{"Grookey"},
{"Thwackey"},
{"Rillaboom"},
{"Scorbunny"},
{"Raboot"},
{"Cinderace"},
{"Sobble"},
{"Drizzile"},
{"Inteleon"},
{"Skwovet"},
{"Greedent"},
{"Rookidee"},
{"Corvisquire"},
{"Corviknight"},
{"Blipbug"},
{"Dottler"},
{"Orbeetle"},
{"Nickit"},
{"Thievul"},
{"Gossifleur"},
{"Eldegoss"},
{"Wooloo"},
{"Dubwool"},
{"Chewtle"},
{"Drednaw"},
{"Yamper"},
{"Boltund"},
{"Rolycoly"},
{"Carkol"},
{"Coalossal"},
{"Applin"},
{"Flapple"},
{"Appletun"},
{"Silicobra"},
{"Sandaconda"},
{"Cramorant"},
{"Arrokuda"},
{"Barraskewda"},
{"Toxel"},
{"Toxtricity"},
{"Sizzlipede"},
{"Centiskorch"},
{"Clobbopus"},
{"Grapploct"},
{"Sinistea"},
{"Polteageist"},
{"Hatenna"},
{"Hattrem"},
{"Hatterene"},
{"Impidimp"},
{"Morgrem"},
{"Grimmsnarl"},
{"Obstagoon"},
{"Perrserker"},
{"Cursola"},
{"Sirfetchd"},
{"Mr Rime"},
{"Runerigus"},
{"Milcery"},
{"Alcremie"},
{"Falinks"},
{"Pincurchin"},
{"Snom"},
{"Frosmoth"},
{"Stonjourner"},
{"Eiscue"},
{"Indeedee"},
{"Morpeko"},
{"Cufant"},
{"Copperajah"},
{"Dracozolt"},
{"Arctozolt"},
{"Dracovish"},
{"Arctovish"},
{"Duraludon"},
{"Dreepy"},
{"Drakloak"},
{"Dragapult"},
{"Zacian"},
{"Zamazenta"},
{"Eternatus"},
{"Kubfu"},
{"Urshifu"},
{"Zarude"},
{"Regieleki"},
{"Regidrago"},
{"Glastrier"},
{"Spectrier"},
{"Calyrex"},
{"Wyrdeer"},
{"Kleavor"},
{"Ursaluna"},
{"Basculegion"},
{"Sneasler"},
{"Overqwil"},
{"Enamorus"},
{"Sprigatito"},
{"Floragato"},
{"Meowscarada"},
{"Fuecoco"},
{"Crocalor"},
{"Skeledirge"},
{"Quaxly"},
{"Quaxwell"},
{"Quaquaval"},
{"Lechonk"},
{"Oinkologne"},
{"Tarountula"},
{"Spidops"},
{"Nymble"},
{"Lokix"},
{"Pawmi"},
{"Pawmo"},
{"Pawmot"},
{"Tandemaus"},
{"Maushold"},
{"Fidough"},
{"Dachsbun"},
{"Smoliv"},
{"Dolliv"},
{"Arboliva"},
{"Squawkabilly"},
{"Nacli"},
{"Naclstack"},
{"Garganacl"},
{"Charcadet"},
{"Armarouge"},
{"Ceruledge"},
{"Tadbulb"},
{"Bellibolt"},
{"Wattrel"},
{"Kilowattrel"},
{"Maschiff"},
{"Mabosstiff"},
{"Shroodle"},
{"Grafaiai"},
{"Bramblin"},
{"Brambleghast"},
{"Toedscool"},
{"Toedscruel"},
{"Klawf"},
{"Capsakid"},
{"Scovillain"},
{"Rellor"},
{"Rabsca"},
{"Flittle"},
{"Espathra"},
{"Tinkatink"},
{"Tinkatuff"},
{"Tinkaton"},
{"Wiglett"},
{"Wugtrio"},
{"Bombirdier"},
{"Finizen"},
{"Palafin"},
{"Varoom"},
{"Revavroom"},
{"Cyclizar"},
{"Orthworm"},
{"Glimmet"},
{"Glimmora"},
{"Greavard"},
{"Houndstone"},
{"Flamigo"},
{"Cetoddle"},
{"Cetitan"},
{"Veluza"},
{"Dondozo"},
{"Tatsugiri"},
{"Annihilape"},
{"Clodsire"},
{"Farigiraf"},
{"Dudunsparce"},
{"Kingambit"},
{"Great Tusk"},
{"Scream Tail"},
{"Brute Bonnet"},
{"Flutter Mane"},
{"Slither Wing"},
{"Sandy Shocks"},
{"Iron Treads"},
{"Iron Bundle"},
{"Iron Hands"},
{"Iron Jugulis"},
{"Iron Moth"},
{"Iron Thorns"},
{"Frigibax"},
{"Arctibax"},
{"Baxcalibur"},
{"Gimmighoul"},
{"Gholdengo"},
{"Wo-Chien"},
{"Chien-Pao"},
{"Ting-Lu"},
{"Chi-Yu"},
{"Roaring Moon"},
{"Iron Valiant"},
{"Koraidon"},
{"Miraidon"},
{"Walking Wake"},
{"Iron Leaves"},
};

static const char *types[] = {
	"None",
	"Normal",
	"Fire",
	"Water",
	"Grass",
	"Electric",
	"Rock",
	"Ground",
	"Ice",
	"Flying",
	"Fighting",
	"Ghost",
	"Bug",
	"Poison",
	"Psychic",
	"Steel",
	"Dark",
	"Dragon",
	"Fairy",
	"Unknown",
	"Shadow",
};

struct PokeInfo {	//must match provided resource data
	uint8_t hp, atk, def, spAtk, spDef, speed, type[2];
} __attribute__((packed));


static const char pokeNameChars[] = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-";

struct BB {
	uint8_t *dst;
	uint16_t buffer;
	uint8_t bitsUsed;
};

static void bbEmit(struct BB *bb, uint8_t val, uint8_t bits)
{
	bb->buffer += ((uint16_t)val) << bb->bitsUsed;
	bb->bitsUsed += bits;
	while (bb->bitsUsed >= 8) {
		*(bb->dst)++ = bb->buffer;
		bb->buffer >>= 8;
		bb->bitsUsed -= 8;
	}
}

static void bbFlush(struct BB *bb)
{
	while (bb->bitsUsed)
		bbEmit(bb, 1, 1);
}

int main(int argc, char** argv)
{
	unsigned i, ofst, numPokes = sizeof(pkmnsNames) / sizeof(*pkmnsNames), prevVal;
	uint8_t compressedData[numPokes][16];
	uint8_t compressedLengths[numPokes];
	struct PokeInfo infos[numPokes];
	
	
	for (i = 0; i < numPokes; i++) {
		
		char fname[32];
		FILE *f;
		
		sprintf(fname, "data/%04u.bin", i + 1);
		f = fopen(fname, "rb");
		if (sizeof(struct PokeInfo) != fread(infos + i, 1, sizeof(struct PokeInfo), f))
			abort();
		fclose(f);
		
		if (infos[i].type[1] == 21)
			infos[i].type[1] = 0;
	}
	
	puts("//pokemon info:");
	puts("// bytes of name (5 bit len, then 6 bits per char: 0-9A-Za-z-)");
	puts("// type (5 bits)");
	puts("// hasSecondType? (1 bit), if so, another 5 bits of type2");
	puts("// stats, one byte each (hp, atk, def, spAtk, spDef, speed)");
	puts("HEX \"INFO\" ID 0");
	
	ofst = 2 * (1 + numPokes);
	
	//compress names and types
	for (i = 0; i < numPokes; i++) {
		
		struct BB bb = {.dst = compressedData[i], };
		unsigned j = 0;
		char name[13];
		
		strcpy(name, pkmnsNames[i]);
		
		while (strlen(name) < 4)	//max len is 11, so with a 3 bit len range we can encode 4..11, extend shorted ones with spaces. this is rare enough to make space savings worth it
			strcat(name, " ");
		
		bbEmit(&bb, strlen(name) - 4, 4);
		char ch;
		
		while ((ch = name[j++]) != 0) {
			
			char *at = strchr(pokeNameChars, ch);
			unsigned encoded;
			
			if (!at) {
				
				fprintf(stderr, "Saw uncompressible char in poke name '%s'. Char was '%c'(%02xh)\n", pkmnsNames[i], ch, ch);
				abort();
			}
			bbEmit(&bb, at - pokeNameChars, 6);
		}
		
		//types
		bbEmit(&bb, infos[i].type[0], 5);
		if (infos[i].type[1]) {
			
			bbEmit(&bb, 1, 1);
			bbEmit(&bb, infos[i].type[1], 5);
		}
		else {
			
			bbEmit(&bb, 0, 1);
		}
		
		bbFlush(&bb);
		compressedLengths[i] = bb.dst - compressedData[i];
	}
	printf("0x%02x 0x%02x //NUM POKEMON\n", (uint8_t)(numPokes >> 8), (uint8_t)numPokes);
	printf("//Now: offsets into this resource for each poke's data. Each poke occupies a minimum of 10 bytes (left as an exercise to you to prove this)\n");
	printf("//each offset is stores as 12 bits. A and B are stored as A.lo (A.hi + 16 * B.hi) B.lo\n");
	printf("//offsets are indexed from the FIRST full byte that follows ALL the offsets\n");
	printf("//offset for poke N is stored as (actual_offset - 10 * N)\n");
	
	ofst = 0;
	prevVal = 0;
	
	for (i = 0; i < numPokes; i++) {
		
		uint32_t effectiveOffset = ofst - 10 * i;
		
		if (effectiveOffset > 0x1000) {
			fprintf(stderr, "offset not encodeable\n");
			abort();
		}
		
		if (i & 1) {	//second value - emit

			printf(" 0x%02x 0x%02x 0x%02x // offsets for pokes %u and %u (%u and %u encoded)\n", 
					(uint8_t)prevVal, (uint8_t)(prevVal >> 8) + (uint8_t)((effectiveOffset >> 8) << 4), (uint8_t)effectiveOffset, i, i + 1, prevVal, effectiveOffset);
		}
		else {			//first value - record
			
			prevVal = effectiveOffset;
		}
		
		ofst += 6 + compressedLengths[i];
	}
	//emit last offset, if any, do not emit 3 bytes when two will do
	if (numPokes & 1) {
		printf(" 0x%02x 0x%02x // offset for pokes %u\n", 
					(uint8_t)prevVal, (uint8_t)(prevVal >> 8), i);
	}
	
	for (i = 0; i < numPokes; i++) {
		
		unsigned j;
		
		
		printf(	"\t//#%u (%s: %-8s %8s):\n"
				"\t\t%-3u %-3u %-3u %-3u %-3u %-3u  //stats\n\t\t",
				i + 1, pkmnsNames[i], types[infos[i].type[0]], types[infos[i].type[1]],
				infos[i].hp, infos[i].atk, infos[i].def, infos[i].spAtk, infos[i].spDef, infos[i].speed);
		
		for (j = 0; j < compressedLengths[i]; j++)
			printf("0x%02x ", compressedData[i][j]);
		printf(" //name and type(s)\n");
	}
	
	puts("\n");
	puts("//pokemon index");
	puts("//first: BE word offsets to start of each of the 26 chains");
	puts("//then: 26 chains.");
	puts("// each chain is a list of BE words, 0-terminated of pokemon starting with that letter in increasing pokemon order");

	
	printf("HEX \"INDX\" ID 0\n");
	uint16_t perLetter[26][1024], pos[26] = {};
	uint32_t totalOfst = 26;
	
	//list pokes by letter
	for (i = 0; i < sizeof(pkmnsNames) / sizeof(*pkmnsNames); i++) {
		
		uint16_t pokeId = i + 1;
		char firstLetter = pkmnsNames[i][0];
		
		if (firstLetter >= 'a' && firstLetter <= 'z')
			firstLetter += 'A' - 'a';
		
		perLetter[firstLetter - 'A'][pos[firstLetter - 'A']++] = pokeId;
	}
	
	//account for the terminators in lengths
	for (i = 0; i < 26; i++)
		perLetter[i][pos[i]++] = 0;
	
	//first the indices into the chain starts
	printf("\t//word offsets of the start of each chain:\n");
	for (i = 0; i < 26; i++) {
		printf(" 0x%02x 0x%02x\n", (uint8_t)(totalOfst >> 8), (uint8_t)totalOfst);
		totalOfst += pos[i];
	}
	printf("\n");
	//now the chains
	for (i = 0; i < 26; i++) {
		unsigned j;
		
		printf("\t//List of pokemon for the letter '%c':\n\t\t", 'A' + i);
		for (j = 0; j < pos[i]; j++) {
			printf("  0x%02x 0x%02x", (uint8_t)(perLetter[i][j] >> 8), (uint8_t)perLetter[i][j]);
		}
		printf("\n");
	}
}