#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>



static char pkmnsNames[][13] = {
{"Bulbizarre"},
{"Herbizarre"},
{"Florizarre"},
{"Salameche"},
{"Reptincel"},
{"Dracaufeu"},
{"Carapuce"},
{"Carabaffe"},
{"Tortank"},
{"Chenipan"},
{"Chrysacier"},
{"Papilusion"},
{"Aspicot"},
{"Coconfort"},
{"Dardargnan"},
{"Roucool"},
{"Roucoups"},
{"Roucarnage"},
{"Rattata"},
{"Rattatac"},
{"Piafabec"},
{"Rapasdepic"},
{"Abo"},
{"Arbok"},
{"Pikachu"},
{"Raichu"},
{"Sabelette"},
{"Sablaireau"},
{"Nidoran"},
{"Nidorina"},
{"Nidoqueen"},
{"Nidoran"},
{"Nidorino"},
{"Nidoking"},
{"Melofee"},
{"Melodelfe"},
{"Goupix"},
{"Feunard"},
{"Rondoudou"},
{"Grodoudou"},
{"Nosferapti"},
{"Nosferalto"},
{"Mystherbe"},
{"Ortide"},
{"Rafflesia"},
{"Paras"},
{"Parasect"},
{"Mimitoss"},
{"Aeromite"},
{"Taupiqueur"},
{"Triopikeur"},
{"Miaouss"},
{"Persian"},
{"Psykokwak"},
{"Akwakwak"},
{"Ferosinge"},
{"Colossinge"},
{"Caninos"},
{"Arcanin"},
{"Ptitard"},
{"Tetarte"},
{"Tartard"},
{"Abra"},
{"Kadabra"},
{"Alakazam"},
{"Machoc"},
{"Machopeur"},
{"Mackogneur"},
{"Chetiflor"},
{"Boustiflor"},
{"Empiflor"},
{"Tentacool"},
{"Tentacruel"},
{"Racaillou"},
{"Gravalanch"},
{"Grolem"},
{"Ponyta"},
{"Galopa"},
{"Ramoloss"},
{"Flagadoss"},
{"Magneti"},
{"Magneton"},
{"Canarticho"},
{"Doduo"},
{"Dodrio"},
{"Otaria"},
{"Lamantine"},
{"Tadmorv"},
{"Grotadmorv"},
{"Kokiyas"},
{"Crustabri"},
{"Fantominus"},
{"Spectrum"},
{"Ectoplasma"},
{"Onix"},
{"Soporifik"},
{"Hypnomade"},
{"Krabby"},
{"Krabboss"},
{"Voltorbe"},
{"Electrode"},
{"Noeunoeuf"},
{"Noadkoko"},
{"Osselait"},
{"Ossatueur"},
{"Kicklee"},
{"Tygnon"},
{"Excelangue"},
{"Smogo"},
{"Smogogo"},
{"Rhinocorne"},
{"Rhinoferos"},
{"Leveinard"},
{"Saquedeneu"},
{"Kangourex"},
{"Hypotrempe"},
{"Hypocean"},
{"Poissirene"},
{"Poissoroy"},
{"Stari"},
{"Staross"},
{"M Mime"},
{"Insecateur"},
{"Lippoutou"},
{"Elektek"},
{"Magmar"},
{"Scarabrute"},
{"Tauros"},
{"Magicarpe"},
{"Leviator"},
{"Lokhlass"},
{"Metamorph"},
{"Evoli"},
{"Aquali"},
{"Voltali"},
{"Pyroli"},
{"Porygon"},
{"Amonita"},
{"Amonistar"},
{"Kabuto"},
{"Kabutops"},
{"Ptera"},
{"Ronflex"},
{"Artikodin"},
{"Electhor"},
{"Sulfura"},
{"Minidraco"},
{"Draco"},
{"Dracolosse"},
{"Mewtwo"},
{"Mew"},
{"Germignon"},
{"Macronium"},
{"Meganium"},
{"Hericendre"},
{"Feurisson"},
{"Typhlosion"},
{"Kaiminus"},
{"Crocrodil"},
{"Aligatueur"},
{"Fouinette"},
{"Fouinar"},
{"Hoothoot"},
{"Noarfang"},
{"Coxy"},
{"Coxyclaque"},
{"Mimigal"},
{"Migalos"},
{"Nostenfer"},
{"Loupio"},
{"Lanturn"},
{"Pichu"},
{"Melo"},
{"Toudoudou"},
{"Togepi"},
{"Togetic"},
{"Natu"},
{"Xatu"},
{"Wattouat"},
{"Lainergie"},
{"Pharamp"},
{"Joliflor"},
{"Marill"},
{"Azumarill"},
{"Simularbre"},
{"Tarpaud"},
{"Granivol"},
{"Floravol"},
{"Cotovol"},
{"Capumain"},
{"Tournegrin"},
{"Heliatronc"},
{"Yanma"},
{"Axoloto"},
{"Maraiste"},
{"Mentali"},
{"Noctali"},
{"Cornebre"},
{"Roigada"},
{"Feuforeve"},
{"Zarbi"},
{"Qulbutoke"},
{"Girafarig"},
{"Pomdepik"},
{"Foretress"},
{"Insolourdo"},
{"Scorplane"},
{"Steelix"},
{"Snubbull"},
{"Granbull"},
{"Qwilfish"},
{"Cizayox"},
{"Caratroc"},
{"Scarhino"},
{"Farfuret"},
{"Teddiursa"},
{"Ursaring"},
{"Limagma"},
{"Volcaropod"},
{"Marcacrin"},
{"Cochignon"},
{"Corayon"},
{"Remoraid"},
{"Octillery"},
{"Cadoizo"},
{"Demanta"},
{"Airmure"},
{"Malosse"},
{"Demolosse"},
{"Hyporoi"},
{"Phanpy"},
{"Donphan"},
{"Porygon2"},
{"Cerfrousse"},
{"Queulorior"},
{"Debugant"},
{"Kapoera"},
{"Lippouti"},
{"Elekid"},
{"Magby"},
{"Ecremeuh"},
{"Leuphorie"},
{"Raikou"},
{"Entei"},
{"Suicune"},
{"Embrylex"},
{"Ymphect"},
{"Tyranocif"},
{"Lugia"},
{"HoOh"},
{"Celebi"},
{"Arcko"},
{"Massko"},
{"Jungko"},
{"Poussifeu"},
{"Galifeu"},
{"Brasegali"},
{"Gobou"},
{"Flobio"},
{"Laggron"},
{"Medhyena"},
{"Grahyena"},
{"Zigzaton"},
{"Lineon"},
{"Chenipotte"},
{"Armulys"},
{"Charmillon"},
{"Blindalys"},
{"Papinox"},
{"Nenupiot"},
{"Lombre"},
{"Ludicolo"},
{"Grainipiot"},
{"Pifeuil"},
{"Tengalice"},
{"Nirondelle"},
{"Heledelle"},
{"Goelise"},
{"Bekipan"},
{"Tarsal"},
{"Kirlia"},
{"Gardevoir"},
{"Arakdo"},
{"Maskadra"},
{"Balignon"},
{"Chapignon"},
{"Parecool"},
{"Vigoroth"},
{"Monaflemit"},
{"Ningale"},
{"Ninjask"},
{"Munja"},
{"Chuchmur"},
{"Ramboum"},
{"Brouhabam"},
{"Makuhita"},
{"Hariyama"},
{"Azurill"},
{"Tarinor"},
{"Skitty"},
{"Delcatty"},
{"Tenefix"},
{"Mysdibule"},
{"Galekid"},
{"Galegon"},
{"Galeking"},
{"Meditikka"},
{"Charmina"},
{"Dynavolt"},
{"Elecsprint"},
{"Posipi"},
{"Negapi"},
{"Muciole"},
{"Lumivole"},
{"Roselia"},
{"Gloupti"},
{"Avaltout"},
{"Carvanha"},
{"Sharpedo"},
{"Wailmer"},
{"Wailord"},
{"Chamallot"},
{"Camerupt"},
{"Chartor"},
{"Spoink"},
{"Groret"},
{"Spinda"},
{"Kraknoix"},
{"Vibraninf"},
{"Libegon"},
{"Cacnea"},
{"Cacturne"},
{"Tylton"},
{"Altaria"},
{"Mangriff"},
{"Seviper"},
{"Seleroc"},
{"Solaroc"},
{"Barloche"},
{"Barbicha"},
{"Ecrapince"},
{"Colhomard"},
{"Balbuto"},
{"Kaorine"},
{"Lilia"},
{"Vacilys"},
{"Anorith"},
{"Armaldo"},
{"Barpau"},
{"Milobellus"},
{"Morpheo"},
{"Kecleon"},
{"Polichombr"},
{"Branette"},
{"Skelenox"},
{"Teraclope"},
{"Tropius"},
{"Eoko"},
{"Absol"},
{"Okeoke"},
{"Stalgamin"},
{"Oniglali"},
{"Obalie"},
{"Phogleur"},
{"Kaimorse"},
{"Coquiperl"},
{"Serpang"},
{"Rosabyss"},
{"Relicanth"},
{"Lovdisc"},
{"Draby"},
{"Drackhaus"},
{"Drattak"},
{"Terhal"},
{"Metang"},
{"Metalosse"},
{"Regirock"},
{"Regice"},
{"Registeel"},
{"Latias"},
{"Latios"},
{"Kyogre"},
{"Groudon"},
{"Rayquaza"},
{"Jirachi"},
{"Deoxys"},
{"Tortipouss"},
{"Boskara"},
{"Torterra"},
{"Ouisticram"},
{"Chimpenfeu"},
{"Simiabraz"},
{"Tiplouf"},
{"Prinplouf"},
{"Pingoleon"},
{"Etourmi"},
{"Etourvol"},
{"Etouraptor"},
{"Keunotor"},
{"Castorno"},
{"Crikzik"},
{"Melokrik"},
{"Lixy"},
{"Luxio"},
{"Luxray"},
{"Rozbouton"},
{"Roserade"},
{"Kranidos"},
{"Charkos"},
{"Dinoclier"},
{"Bastiodon"},
{"Cheniti"},
{"Cheniselle"},
{"Papilord"},
{"Apitrini"},
{"Apireine"},
{"Pachirisu"},
{"Mustebouee"},
{"Musteflott"},
{"Ceribou"},
{"Ceriflor"},
{"Sancoki"},
{"Tritosor"},
{"Capidextre"},
{"Baudrive"},
{"Grodrive"},
{"Laporeille"},
{"Lockpin"},
{"Magireve"},
{"Corboss"},
{"Chaglam"},
{"Chaffreux"},
{"Korillon"},
{"Moufouette"},
{"Moufflair"},
{"Archeomire"},
{"Archeodong"},
{"Manzai"},
{"Mime Jr"},
{"Ptiravi"},
{"Pijako"},
{"Spiritomb"},
{"Griknot"},
{"Carmache"},
{"Carchacrok"},
{"Goinfrex"},
{"Riolu"},
{"Lucario"},
{"Hippopotas"},
{"Hippodocus"},
{"Rapion"},
{"Drascore"},
{"Cradopaud"},
{"Coatox"},
{"Vortente"},
{"Ecayon"},
{"Lumineon"},
{"Babimanta"},
{"Blizzi"},
{"Blizzaroi"},
{"Dimoret"},
{"Magnezone"},
{"Coudlangue"},
{"Rhinastoc"},
{"Bouldeneu"},
{"Elekable"},
{"Maganon"},
{"Togekiss"},
{"Yanmega"},
{"Phyllali"},
{"Givrali"},
{"Scorvol"},
{"Mammochon"},
{"PorygonZ"},
{"Gallame"},
{"Tarinorme"},
{"Noctunoir"},
{"Momartik"},
{"Motisma"},
{"Crehelf"},
{"Crefollet"},
{"Crefadet"},
{"Dialga"},
{"Palkia"},
{"Heatran"},
{"Regigigas"},
{"Giratina"},
{"Cresselia"},
{"Phione"},
{"Manaphy"},
{"Darkrai"},
{"Shaymin"},
{"Arceus"},
{"Victini"},
{"Vipelierre"},
{"Lianaja"},
{"Majaspic"},
{"Gruikui"},
{"Grotichon"},
{"Roitiflam"},
{"Moustillon"},
{"Mateloutre"},
{"Clamiral"},
{"Ratentif"},
{"Miradar"},
{"Ponchiot"},
{"Ponchien"},
{"Mastouffe"},
{"Chacripan"},
{"Leopardus"},
{"Feuillajou"},
{"Feuiloutan"},
{"Flamajou"},
{"Flamoutan"},
{"Flotajou"},
{"Flotoutan"},
{"Munna"},
{"Mushana"},
{"Poichigeon"},
{"Colombeau"},
{"Deflaisan"},
{"Zebribon"},
{"Zeblitz"},
{"Nodulithe"},
{"Geolithe"},
{"Gigalithe"},
{"Chovsourir"},
{"Rhinolove"},
{"Rototaupe"},
{"Minotaupe"},
{"Nanmeouie"},
{"Charpenti"},
{"Ouvrifier"},
{"Betochef"},
{"Tritonde"},
{"Batracne"},
{"Crapustule"},
{"Judokrak"},
{"Karaclee"},
{"Larveyette"},
{"Couverdure"},
{"Manternel"},
{"Venipatte"},
{"Scobolide"},
{"Brutapode"},
{"Doudouvet"},
{"Farfaduvet"},
{"Chlorobule"},
{"Fragilady"},
{"Bargantua"},
{"Mascaiman"},
{"Escroco"},
{"Crocorible"},
{"Darumarond"},
{"Darumacho"},
{"Maracachi"},
{"Crabicoque"},
{"Crabaraque"},
{"Baggiguane"},
{"Baggaid"},
{"Cryptero"},
{"Tutafeh"},
{"Tutankafer"},
{"Carapagos"},
{"Megapagos"},
{"Arkeapti"},
{"Aeropteryx"},
{"Miamiasme"},
{"Miasmax"},
{"Zorua"},
{"Zoroark"},
{"Chinchidou"},
{"Pashmilla"},
{"Scrutella"},
{"Mesmerella"},
{"Siderella"},
{"Nucleos"},
{"Meios"},
{"Symbios"},
{"Couaneton"},
{"Lakmecygne"},
{"Sorbebe"},
{"Sorboul"},
{"Sorbouboul"},
{"Vivaldaim"},
{"Haydaim"},
{"Emolga"},
{"Carabing"},
{"Lancargot"},
{"Trompignon"},
{"Gaulet"},
{"Viskuse"},
{"Moyade"},
{"Mamanbo"},
{"Statitik"},
{"Mygavolt"},
{"Grindur"},
{"Noacier"},
{"Tic"},
{"Clic"},
{"Cliticlic"},
{"Anchwatt"},
{"Lamperoie"},
{"Ohmassacre"},
{"Lewsor"},
{"Neitram"},
{"Funecire"},
{"Melancolux"},
{"Lugulabre"},
{"Coupenotte"},
{"Incisache"},
{"Tranchodon"},
{"Polarhume"},
{"Polagriffe"},
{"Hexagel"},
{"Escargaume"},
{"Limaspeed"},
{"Limonde"},
{"Kungfouine"},
{"Shaofouine"},
{"Drakkarmin"},
{"Gringolem"},
{"Golemastoc"},
{"Scalpion"},
{"Scalproie"},
{"Frison"},
{"Furaiglon"},
{"Gueriaigle"},
{"Vostourno"},
{"Vaututrice"},
{"Aflamanoir"},
{"Fermite"},
{"Solochi"},
{"Diamat"},
{"Trioxhydre"},
{"Pyronille"},
{"Pyrax"},
{"Cobaltium"},
{"Terrakium"},
{"Viridium"},
{"Boreas"},
{"Fulguris"},
{"Reshiram"},
{"Zekrom"},
{"Demeteros"},
{"Kyurem"},
{"Keldeo"},
{"Meloetta"},
{"Genesect"},
{"Marisson"},
{"Boguerisse"},
{"Blindepique"},
{"Feunnec"},
{"Roussil"},
{"Goupelin"},
{"Grenousse"},
{"Croaporal"},
{"Amphinobi"},
{"Sapereau"},
{"Excavarenne"},
{"Passerouge"},
{"Braisillon"},
{"Flambusard"},
{"Lepidonille"},
{"Peregrain"},
{"Prismillon"},
{"Helionceau"},
{"Nemelios"},
{"Flabebe"},
{"Floette"},
{"Florges"},
{"Cabriolaine"},
{"Chevroum"},
{"Pandespiegle"},
{"Pandarbare"},
{"Couafarel"},
{"Psystigri"},
{"Mistigrix"},
{"Monorpale"},
{"Dimocles"},
{"Exagide"},
{"Fluvetin"},
{"Cocotine"},
{"Sucroquin"},
{"Cupcanaille"},
{"Sepiatop"},
{"Sepiatroce"},
{"Opermine"},
{"Golgopathe"},
{"Venalgue"},
{"Kravarech"},
{"Flingouste"},
{"Gamblast"},
{"Galvaran"},
{"Iguolta"},
{"Ptyranidur"},
{"Rexillius"},
{"Amagara"},
{"Dragmara"},
{"Nymphali"},
{"Brutalibre"},
{"Dedenne"},
{"Strassie"},
{"Mucuscule"},
{"Colimucus"},
{"Muplodocus"},
{"Trousselin"},
{"Brocelome"},
{"Desseliande"},
{"Pitrouille"},
{"Banshitrouye"},
{"Grelacon"},
{"Seracrawl"},
{"Sonistrelle"},
{"Bruyverne"},
{"Xerneas"},
{"Yveltal"},
{"Zygarde"},
{"Diancie"},
{"Hoopa"},
{"Volcanion"},
{"Brindibou"},
{"Effleche"},
{"Archeduc"},
{"Flamiaou"},
{"Matoufeu"},
{"Felinferno"},
{"Otaquin"},
{"Otarlette"},
{"Oratoria"},
{"Picassaut"},
{"Piclairon"},
{"Bazoucan"},
{"Manglouton"},
{"Argouste"},
{"Larvibule"},
{"Chrysapile"},
{"Lucanon"},
{"Crabagarre"},
{"Crabominable"},
{"Plumeline"},
{"Bombydou"},
{"Rubombelle"},
{"Rocabot"},
{"Lougaroc"},
{"Froussardine"},
{"Vorasterie"},
{"Predasterie"},
{"Tiboudet"},
{"Bourrinos"},
{"Araqua"},
{"Tarenbulle"},
{"Mimantis"},
{"Floramantis"},
{"Spododo"},
{"Lampignon"},
{"Tritox"},
{"Malamandre"},
{"Nounourson"},
{"Chelours"},
{"Croquine"},
{"Candine"},
{"Sucreine"},
{"Guerilande"},
{"Gouroutan"},
{"Quartermac"},
{"Sovkipou"},
{"Sarmurai"},
{"Bacabouh"},
{"Trepassable"},
{"Concombaffe"},
{"Type0"},
{"Silvallie"},
{"Meteno"},
{"Dodoala"},
{"Boumata"},
{"Togedemaru"},
{"Mimiqui"},
{"Denticrisse"},
{"Draieul"},
{"Sinistrail"},
{"Bebecaille"},
{"Ecaid"},
{"Ekaiser"},
{"Tokorico"},
{"Tokopiyon"},
{"Tokotoro"},
{"Tokopisco"},
{"Cosmog"},
{"Cosmovum"},
{"Solgaleo"},
{"Lunala"},
{"Zeroid"},
{"Mouscoto"},
{"Cancrelove"},
{"Cablifere"},
{"Bamboiselle"},
{"Katagami"},
{"Engloutyran"},
{"Necrozma"},
{"Magearna"},
{"Marshadow"},
{"Vemini"},
{"Mandrillon"},
{"AmaAma"},
{"Pierroteknik"},
{"Zeraora"},
{"Meltan"},
{"Melmetal"},
{"Ouistempo"},
{"Badabouin"},
{"Gorythmic"},
{"Flambino"},
{"Lapyro"},
{"Pyrobut"},
{"Larmeleon"},
{"Arrozard"},
{"Lezargus"},
{"Rongourmand"},
{"Rongrigou"},
{"Minisange"},
{"Bleuseille"},
{"Corvaillus"},
{"Larvadar"},
{"Coleodome"},
{"Astronelle"},
{"Goupilou"},
{"Roublenard"},
{"Tournicoton"},
{"Blancoton"},
{"Moumouton"},
{"Moumouflon"},
{"Khelocrok"},
{"Torgamord"},
{"Voltoutou"},
{"Fulgudog"},
{"Charbi"},
{"Wagomine"},
{"Monthracite"},
{"Verpom"},
{"Pomdrapi"},
{"Dratatin"},
{"Dunaja"},
{"Dunaconda"},
{"Nigosier"},
{"Embrochet"},
{"Hastacuda"},
{"Toxizap"},
{"Salarsen"},
{"Grillepattes"},
{"Scolocendre"},
{"Poulpaf"},
{"Krakos"},
{"Theffroi"},
{"Polthegeist"},
{"Bibichut"},
{"Chapotus"},
{"Sorcilence"},
{"Grimalin"},
{"Fourbelin"},
{"Angoliath"},
{"Ixon"},
{"Berserkatt"},
{"Corayome"},
{"Palarticho"},
{"M Glaquette"},
{"Tutetekri"},
{"Cremy"},
{"Charmilly"},
{"Hexadron"},
{"Wattapik"},
{"Frissonille"},
{"Beldeneige"},
{"Dolman"},
{"Bekaglacon"},
{"Wimessir"},
{"Morpeko"},
{"Charibari"},
{"Pachyradjah"},
{"Galvagon"},
{"Galvagla"},
{"Hydragon"},
{"Hydragla"},
{"Duralugon"},
{"Fantyrm"},
{"Dispareptil"},
{"Lanssorien"},
{"Zacian"},
{"Zamazenta"},
{"Ethernatos"},
{"Wushours"},
{"Shifours"},
{"Zarude"},
{"Regieleki"},
{"Regidrago"},
{"Blizzeval"},
{"Spectreval"},
{"Sylveroy"},
{"Cerbyllin"},
{"Hachecateur"},
{"Ursaking"},
{"Paragruel"},
{"Farfurex"},
{"Qwilpik"},
{"Amovenus"},
{"Poussacha"},
{"Matourgeon"},
{"Miascarade"},
{"Chochodile"},
{"Crocogril"},
{"Flamigator"},
{"Coiffeton"},
{"Canarbello"},
{"Palmaval"},
{"Gourmelet"},
{"Fragroin"},
{"Tissenboule"},
{"Filentrappe"},
{"Lilliterelle"},
{"Gambex"},
{"Pohm"},
{"Pohmotte"},
{"Pohmarmotte"},
{"Compagnol"},
{"Famignol"},
{"Patachiot"},
{"Briochien"},
{"Olivini"},
{"Olivado"},
{"Arboliva"},
{"Tapatoes"},
{"Selutin"},
{"Amassel"},
{"Gigansel"},
{"Charbambin"},
{"Carmadura"},
{"Malvalame"},
{"Tetampoule"},
{"Ampibidou"},
{"Zapetrel"},
{"Fulgulairo"},
{"Grondogue"},
{"Dogrino"},
{"Gribouraigne"},
{"TagTag"},
{"Virovent"},
{"Virevorreur"},
{"Terracool"},
{"Terracruel"},
{"Craparoi"},
{"Pimito"},
{"Scovilain"},
{"Leboulerou"},
{"Berasca"},
{"Flotillon"},
{"Cleopsytra"},
{"Forgerette"},
{"Forgella"},
{"Forgelina"},
{"Taupikeau"},
{"Triopikeau"},
{"Lestombaile"},
{"Dofin"},
{"Superdofin"},
{"Vrombi"},
{"Vrombotor"},
{"Motorizard"},
{"Ferdeter"},
{"Germeclat"},
{"Floreclat"},
{"Toutombe"},
{"Tomberro"},
{"Flamenroule"},
{"Pietace"},
{"Balbaleze"},
{"Delestin"},
{"Oyacata"},
{"Nigirigon"},
{"Courrousinge"},
{"Terraiste"},
{"Farigiraf"},
{"Deusolourdo"},
{"Scalpereur"},
{"FortIvoire"},
{"HurleQueue"},
{"FongusFurie"},
{"FlotteMeche"},
{"RampeAiles"},
{"PelageSable"},
{"RouedeFer"},
{"HottedeFer"},
{"PaumedeFer"},
{"TetesdeFer"},
{"MitedeFer"},
{"EpinedeFer"},
{"Frigodo"},
{"Cryodo"},
{"Glaivodo"},
{"Mordudor"},
{"Gromago"},
{"Chongjian"},
{"Baojian"},
{"Dinglu"},
{"Yuyu"},
{"RugitLune"},
{"GardedeFer"},
{"Koraidon"},
{"Miraidon"},
{"SerpenteEau"},
{"VertdeFer"}
};

static const char *types[] = {
	"None",
	"Normal",
	"Fire",
	"Water",
	"Grass",
	"Electric",
	"Rock",
	"Ground",
	"Ice",
	"Flying",
	"Fighting",
	"Ghost",
	"Bug",
	"Poison",
	"Psychic",
	"Steel",
	"Dark",
	"Dragon",
	"Fairy",
	"Unknown",
	"Shadow",
};

struct PokeInfo {	//must match provided resource data
	uint8_t hp, atk, def, spAtk, spDef, speed, type[2];
} __attribute__((packed));


static const char pokeNameChars[] = " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-";

struct BB {
	uint8_t *dst;
	uint16_t buffer;
	uint8_t bitsUsed;
};

static void bbEmit(struct BB *bb, uint8_t val, uint8_t bits)
{
	bb->buffer += ((uint16_t)val) << bb->bitsUsed;
	bb->bitsUsed += bits;
	while (bb->bitsUsed >= 8) {
		*(bb->dst)++ = bb->buffer;
		bb->buffer >>= 8;
		bb->bitsUsed -= 8;
	}
}

static void bbFlush(struct BB *bb)
{
	while (bb->bitsUsed)
		bbEmit(bb, 1, 1);
}

int main(int argc, char** argv)
{
	unsigned i, ofst, numPokes = sizeof(pkmnsNames) / sizeof(*pkmnsNames), prevVal;
	uint8_t compressedData[numPokes][16];
	uint8_t compressedLengths[numPokes];
	struct PokeInfo infos[numPokes];

	for (i = 0; i < numPokes; i++) {
		
		char fname[32];
		FILE *f;
		
		sprintf(fname, "data/%04u.bin", i + 1);
		f = fopen(fname, "rb");
		if (sizeof(struct PokeInfo) != fread(infos + i, 1, sizeof(struct PokeInfo), f))
			abort();
		fclose(f);
		
		if (infos[i].type[1] == 21)
			infos[i].type[1] = 0;
	}
	
	puts("//pokemon info:");
	puts("// bytes of name (5 bit len, then 6 bits per char: 0-9A-Za-z-)");
	puts("// type (5 bits)");
	puts("// hasSecondType? (1 bit), if so, another 5 bits of type2");
	puts("// stats, one byte each (hp, atk, def, spAtk, spDef, speed)");
	puts("HEX \"INFO\" ID 0");
	
	ofst = 2 * (1 + numPokes);
	
	//compress names and types
	for (i = 0; i < numPokes; i++) {
		
		struct BB bb = {.dst = compressedData[i], };
		unsigned j = 0;
		char name[13];
		
		strcpy(name, pkmnsNames[i]);
		
		while (strlen(name) < 4)	//max len is 11, so with a 3 bit len range we can encode 4..11, extend shorted ones with spaces. this is rare enough to make space savings worth it
			strcat(name, " ");

		if (strlen(name) > 12)
		{
			fprintf(stderr, "Saw name too long '%s'\n", pkmnsNames[i]);
			abort();
		}
		
		bbEmit(&bb, strlen(name) - 4, 4);
		char ch;
		
		while ((ch = name[j++]) != 0) {
			
			char *at = strchr(pokeNameChars, ch);
			unsigned encoded;
			
			if (!at) {
				
				fprintf(stderr, "Saw uncompressible char in poke name '%s'. Char was '%c'(%02xh)\n", pkmnsNames[i], ch, ch);
				abort();
			}
			bbEmit(&bb, at - pokeNameChars, 6);
		}
		
		//types
		bbEmit(&bb, infos[i].type[0], 5);
		if (infos[i].type[1]) {
			
			bbEmit(&bb, 1, 1);
			bbEmit(&bb, infos[i].type[1], 5);
		}
		else {
			
			bbEmit(&bb, 0, 1);
		}
		
		bbFlush(&bb);
		compressedLengths[i] = bb.dst - compressedData[i];
	}
	printf("0x%02x 0x%02x //NUM POKEMON\n", (uint8_t)(numPokes >> 8), (uint8_t)numPokes);
	printf("//Now: offsets into this resource for each poke's data. Each poke occupies a minimum of 10 bytes (left as an exercise to you to prove this)\n");
	printf("//each offset is stores as 12 bits. A and B are stored as A.lo (A.hi + 16 * B.hi) B.lo\n");
	printf("//offsets are indexed from the FIRST full byte that follows ALL the offsets\n");
	printf("//offset for poke N is stored as a full 16-bit BE word: (actual_offset - 10 * N)\n");
	
	//
	// Emit each offset as a 16‑bit big‑endian word (2 bytes per entry):
	//
	ofst = 0;
	for (i = 0; i < numPokes; i++) {
		uint32_t effectiveOffset = ofst - 10 * i;

		if (effectiveOffset > 0xFFFF) {
			fprintf(stderr, "offset not encodeable (max 0xFFFF)\n");
			abort();
		}

		// high byte, then low byte:
		printf(" 0x%02x 0x%02x // offset for poke %u\n",
				(uint8_t)(effectiveOffset >> 8),
				(uint8_t)(effectiveOffset & 0xFF),
				i + 1);

		ofst += 6 + compressedLengths[i];
	}
	
	for (i = 0; i < numPokes; i++) {
		
		unsigned j;
		
		
		printf(	"\t//#%u (%s: %-8s %8s):\n"
				"\t\t%-3u %-3u %-3u %-3u %-3u %-3u  //stats\n\t\t",
				i + 1, pkmnsNames[i], types[infos[i].type[0]], types[infos[i].type[1]],
				infos[i].hp, infos[i].atk, infos[i].def, infos[i].spAtk, infos[i].spDef, infos[i].speed);
		
		for (j = 0; j < compressedLengths[i]; j++)
			printf("0x%02x ", compressedData[i][j]);
		printf(" //name and type(s)\n");
	}
	
	puts("\n");
	puts("//pokemon index");
	puts("//first: BE word offsets to start of each of the 26 chains");
	puts("//then: 26 chains.");
	puts("// each chain is a list of BE words, 0-terminated of pokemon starting with that letter in increasing pokemon order");

	
	printf("HEX \"INDX\" ID 0\n");
	uint16_t perLetter[26][1024], pos[26] = {};
	uint32_t totalOfst = 26;
	
	//list pokes by letter
	for (i = 0; i < sizeof(pkmnsNames) / sizeof(*pkmnsNames); i++) {
		
		uint16_t pokeId = i + 1;
		char firstLetter = pkmnsNames[i][0];
		
		if (firstLetter >= 'a' && firstLetter <= 'z')
			firstLetter += 'A' - 'a';
		
		perLetter[firstLetter - 'A'][pos[firstLetter - 'A']++] = pokeId;
	}
	
	//account for the terminators in lengths
	for (i = 0; i < 26; i++)
		perLetter[i][pos[i]++] = 0;
	
	//first the indices into the chain starts
	printf("\t//word offsets of the start of each chain:\n");
	for (i = 0; i < 26; i++) {
		printf(" 0x%02x 0x%02x\n", (uint8_t)(totalOfst >> 8), (uint8_t)totalOfst);
		totalOfst += pos[i];
	}
	printf("\n");
	//now the chains
	for (i = 0; i < 26; i++) {
		unsigned j;
		
		printf("\t//List of pokemon for the letter '%c':\n\t\t", 'A' + i);
		for (j = 0; j < pos[i]; j++) {
			printf("  0x%02x 0x%02x", (uint8_t)(perLetter[i][j] >> 8), (uint8_t)perLetter[i][j]);
		}
		printf("\n");
	}
}